# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ad4292abb27b8c4a7a5011bebc703bac358d13b2993a3eb5a79a35a31578e771c4a9d96450b8247a40b477bf778503622fa9d09846112b647fb80d48a975df

test:
  secret_key_base: 0d9aa24435546bdcf5923796433d59736a2c33a1e555e03458714e4f668ba9154520aa798a6898a81db4320d8a302b066fefb71c3e4f3aa2db3847c26e0c02a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
